name: Code Style Check

on:
    pull_request:
    push:
        branches:
            - main

jobs:
  eslint_check_upload:
    runs-on: ubuntu-latest
    name: ESLint Check and Report Upload

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Packages
        run: NODE_OPTIONS='--max-old-space-size=4096' pnpm build:all
      - name: Eslint Check
        run: pnpm turbo run lint
      - name: Save Code Linting Report JSON
        run: pnpm lint:report
        # Continue to the next step even if this fails
        continue-on-error: true
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report.json
          path: eslint_report.json

  annotation:
    # Skip the annotation action in push events
    if: github.event_name == 'pull_request'
    needs: eslint_check_upload
    runs-on: ubuntu-latest
    name: ESLint Annotation
    permissions:
      pull-requests: read
      checks: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: eslint_report.json
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@d57a1193d4c59cbfbf3f86c271f42612f9dbd9e9 # v3
        with:
          report-json: 'eslint_report.json'

  prettier_check:
    runs-on: ubuntu-latest
    name: Format Check
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Prettier Check
        run: pnpm prettier --check '**/*.{ts,md}'
